defaults: &defaults
  name: 'kittyballs'
  hostname: '192.168.1.107'
  demo:
    tokboxSessionId: '1_MX4yMzAxNzU1Mn4xMjcuMC4wLjF-U2F0IEZlYiAyMyAwODowNTowMiBQU1QgMjAxM34wLjk1Nzc4OTk2fg'
    tokboxPublisherToken: 'T1==cGFydG5lcl9pZD0yMzAxNzU1MiZzZGtfdmVyc2lvbj10YnJ1YnktdGJyYi12MC45MS4yMDExLTAyLTE3JnNpZz04ZDQ4MTE3MGQ4NTljNWVhMTU0MzY5YzBiNDM2NzI0ZTdiY2FkNDc2OnJvbGU9cHVibGlzaGVyJnNlc3Npb25faWQ9MV9NWDR5TXpBeE56VTFNbjR4TWpjdU1DNHdMakYtVTJGMElFWmxZaUF5TXlBd09Eb3dOVG93TWlCUVUxUWdNakF4TTM0d0xqazFOemM0T1RrMmZnJmNyZWF0ZV90aW1lPTEzNjE2Mzg0MDMmbm9uY2U9MC4zNzI3OTkzNTg2OTgxNDA1JmV4cGlyZV90aW1lPTEzNjQyMzA0MDMmY29ubmVjdGlvbl9kYXRhPQ=='
    tokboxSubscriberToken: 'T1==cGFydG5lcl9pZD0yMzAxNzU1MiZzZGtfdmVyc2lvbj10YnJ1YnktdGJyYi12MC45MS4yMDExLTAyLTE3JnNpZz02ZjY5MGRiMjk3ZGUyZjc0MDE2NmExZjM5ZjViNmQ4YTllODA1YTczOnJvbGU9c3Vic2NyaWJlciZzZXNzaW9uX2lkPTFfTVg0eU16QXhOelUxTW40eE1qY3VNQzR3TGpGLVUyRjBJRVpsWWlBeU15QXdPRG93TlRvd01pQlFVMVFnTWpBeE0zNHdMamsxTnpjNE9UazJmZyZjcmVhdGVfdGltZT0xMzYxNjM1NTA5Jm5vbmNlPTAuNTg2MTc0OTc3NTI0OTExNCZleHBpcmVfdGltZT0xMzY0MjI3NTEwJmNvbm5lY3Rpb25fZGF0YT0='
  tokbox:
    apikey: '23017552'
    apisecret: '84422894312a8a571300182f874a3d82af27f426'
development:
  <<: *defaults
  port: 5000
  redis:
    url: 'redis://:@localhost:6379/'
  
test:
  <<: *defaults
  hostname: 'www.kittyballs.org'
  port:: {{ env.PORT }}
  redis:
    url: {{ env.REDISTOGO_URL }}

production:
  <<: *defaults
  port: {{ env.PORT }}
  redis:
    url: {{ env.REDISTOGO_URL }}
